---
title: "DADA2 Tuto nb"
output: html_notebook
---

```{r}
library(dada2)
```

```{r}
install.packages("Rcpp")
```
```{r}
library(dada2)
```

```{r}
packageVersion("dada2")
```

```{r}
path<- "/home/rstudio/DADA2/MiSeq_SOP"
```

```{r}
path
```

```{r}
list.files(path)
```

```{r}
fnFs<-sort(list.files(path, pattern="_R1_001.fastq", full.names=TRUE))
fnFs
```

```{r}
fnRs<-sort(list.files(path, pattern="_R2_001.fastq",full.names=TRUE))
fnRs
```

```{r}
sample.names<-sapply(strsplit(basename(fnFs),"_"),`[`, 1)
sample.names<-sapply(strsplit(basename(fnRs),"_"),`[`, 1)
sample.names
```

```{r}
plotQualityProfile(fnFs[1:2])
```

```{r}
plotQualityProfile(fnRs[1:2])
```

```{r}
filtFs<-file.path(path,"filtered",paste0(sample.names,"_F_filt.fastq.gz"))
filtRs<-file.path(path,"filtered",paste0(sample.names,"_R_filt.fastq.gz"))
```

```{r}
out<-filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(240,160),maxN=0,maxEE=c(2,2),truncQ=2,rm.phix=TRUE,compress=TRUE,multithread=TRUE)
```
```{r}
head(out)
```

```{r}
errF<-learnErrors(filtFs, multithread=TRUE)
errR<-learnErrors(filtRs, multithread=TRUE)
```
```{r}
plotErrors(errF,nominalQ=TRUE)
```
```{r}
dadaFs<-dada(filtFs, err=errF, multithread=TRUE)
dadaRs<-dada(filtRs, err=errR, multithread=TRUE)
```

```{r}
dadaFs[[16]]
```
```{r}
mergers<-mergePairs(dadaFs,filtFs,dadaRs,filtRs, verbose=TRUE)
head(mergers[[1]])
```

```{r}
seqtab<-makeSequenceTable(mergers)
dim(seqtab)
table(nchar(getSequences(seqtab)))
```

```{r}
seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=TRUE, verbose=TRUE)
dim(seqtab.nochim)
sum(seqtab.nochim)/sum(seqtab)
```

```{r}
getN <- function(x) sum(getUniques(x))
track <- cbind(out, sapply(dadaFs, getN), sapply(dadaRs, getN), sapply(mergers, getN), rowSums(seqtab.nochim))
```

```{r}
colnames(track) <- c("input", "filtered", "denoisedF", "denoisedR", "merged", "nonchim")
rownames(track) <- sample.names
head(track)
```

```{r}
taxa <- assignTaxonomy(seqtab.nochim, "/Home/rstudio/DADA2/silva_nr_v132_train_set.fa.gz", multithread=TRUE)
```

